### Pandas-DataFrame And Series

Pandas is a powerful data manipulation liabrary in Python , widely used for data analysis and data cleaning . It provides two primary data structures: Series and DataFrame. A Series is a one dimensional array-like object , while a DataFrame is a two dimensional, size-mutable and potentially heterogenous tabular data structure
with labeled axes (rows and columns).

In [2]:
! pip install pandas

Requirement already satisfied: pandas in c:\Users\669ra\Desktop\Data-Analyst\Python\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\669ra\Desktop\Data-Analyst\Python\venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\669ra\Desktop\Data-Analyst\Python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\669ra\Desktop\Data-Analyst\Python\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\669ra\Desktop\Data-Analyst\Python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
## Series
## A Pandas Series is a one dimensional array-Like object that can hold any data type. It is similar to a columnn in a Table.

import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print("Series: \n " , series)
print(type(series))

Series:
  0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create a series from Dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [8]:
## DataFrame
## Create a dataframe from a dictionary of list

data={
    'Name':['Raj','Sharma','John'],
    'Age':[22,33,44],
    'City':['Banglore','NewYork','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0     Raj   22  Banglore
1  Sharma   33   NewYork
2    John   44   Florida
<class 'pandas.DataFrame'>

In [9]:
import numpy as np
np.array(df)

array([['Raj', 22, 'Banglore'],
       ['Sharma', 33, 'NewYork'],
       ['John', 44, 'Florida']], dtype=object)

In [21]:
## Create a DataFrame from a list of Dictionaries

data=[
    {'Name':'Raj','Age':32,'City':'Banglore'},
    {'Name':'Sharma','Age':32,'City':'Banglore'},
    {'Name':'Krish','Age':32,'City':'Banglore'},
    {'Name':'Jack','Age':32,'City':'Banglore'},
]

df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0     Raj   32  Banglore
1  Sharma   32  Banglore
2   Krish   32  Banglore
3    Jack   32  Banglore
<class 'pandas.DataFrame'>

In [ ]:
d_f=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
d_f=pd.read_csv('data.csv')
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [22]:
## Accessing data from dataframes

df

     Name  Age      City
0     Raj   32  Banglore
1  Sharma   32  Banglore
2   Krish   32  Banglore
3    Jack   32  Banglore

In [25]:
df['Name']

0       Raj
1    Sharma
2     Krish
3      Jack
Name: Name, dtype: str

In [ ]:
df.loc[0] ## Row index # Location

Name         Raj
Age           32
City    Banglore
Name: 0, dtype: object

In [ ]:
df.iloc[0] ## index Location

Name         Raj
Age           32
City    Banglore
Name: 0, dtype: object

In [40]:
df

     Name  Age      City
0     Raj   32  Banglore
1  Sharma   32  Banglore
2   Krish   32  Banglore
3    Jack   32  Banglore

In [41]:
## Accessing a specified element
df.at[1,'Age']

np.int64(32)

In [42]:
## Accessing specified element using  iat
df.iat[2,2]

'Banglore'

In [55]:
## Data manipulation with DataFrames

df

     Name  Age      City  salary
0     Raj   32  Banglore   50000
1  Sharma   32  Banglore   60000
2   Krish   32  Banglore   70000
3    Jack   32  Banglore   40000

In [ ]:
## Adding a column

df['Salary']=[50000,60000,70000,40000]
df

In [61]:
## Remove a column
df.drop('salary',axis=1,inplace=True)

In [62]:
df

     Name  Age      City
0     Raj   32  Banglore
1  Sharma   32  Banglore
2   Krish   32  Banglore
3    Jack   32  Banglore

In [63]:
## Add age to the column

df['Age']=df['Age']+1

In [64]:
df

     Name  Age      City
0     Raj   33  Banglore
1  Sharma   33  Banglore
2   Krish   33  Banglore
3    Jack   33  Banglore

In [67]:
df.drop(0,inplace=True)

In [68]:
df

     Name  Age      City
1  Sharma   33  Banglore
2   Krish   33  Banglore
3    Jack   33  Banglore

In [70]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [74]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [72]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object